import { ProductData } from '../product/product-data';

export const productList: ProductData[] = [
    {
        id : 1,
        prod_name : 'pizza',
        prod_image : '',
        prod_seller : 'jeo',
        prod_variant : '1',
        prod_category : 'food',
        txt_pack_type : '',
        prod_isReturnable : 'yes',
        prod_price_selling : '309',
        prod_discount : '12',
        prod_price_offer : '140',
        prod_price_total : '150',
        prod_discount_added : '10',
        prod_stock : '3',
        prod_expiry_date : '1/2/2222',
        txt_county : 'india',
    },
    {
        id : 2,
        prod_name : 'Burgar',
        prod_image : '',
        prod_seller : 'jeo',
        prod_variant : '1',
        prod_category : 'food',
        txt_pack_type : '',
        prod_isReturnable : 'yes',
        prod_price_selling : '103',
        prod_discount : '12',
        prod_price_offer : '140',
        prod_price_total : '150',
        prod_discount_added : '10',
        prod_stock : '3',
        prod_expiry_date : '1/2/2222',
        txt_county : 'india',
    },
    {
        id : 3,
        prod_name : 'pant',
        prod_image : '',
        prod_seller : 'jeo',
        prod_variant : '1',
        prod_category : 'dress',
        txt_pack_type : '',
        prod_isReturnable : 'yes',
        prod_price_selling : '345',
        prod_discount : '12',
        prod_price_offer : '140',
        prod_price_total : '150',
        prod_discount_added : '10',
        prod_stock : '3',
        prod_expiry_date : '1/2/2222',
        txt_county : 'india',
    },
    {
        id : 4,
        prod_name : 'shirt',
        prod_image : '',
        prod_seller : 'jeo',
        prod_variant : '1',
        prod_category : 'dress',
        txt_pack_type : '',
        prod_isReturnable : 'yes',
        prod_price_selling : '1200',
        prod_discount : '12',
        prod_price_offer : '140',
        prod_price_total : '150',
        prod_discount_added : '10',
        prod_stock : '3',
        prod_expiry_date : '1/2/2222',
        txt_county : 'india',
    },
    {
        id : 5,
        prod_name : 'computer',
        prod_image : '',
        prod_seller : 'jeo',
        prod_variant : '1',
        prod_category : 'electrical',
        txt_pack_type : '',
        prod_isReturnable : 'yes',
        prod_price_selling : '1000',
        prod_discount : '12',
        prod_price_offer : '140',
        prod_price_total : '150',
        prod_discount_added : '10',
        prod_stock : '3',
        prod_expiry_date : '1/2/2222',
        txt_county : 'india',
    },
    {
        id : 6,
        prod_name : 'headset',
        prod_image : '',
        prod_seller : 'jeo',
        prod_variant : '1',
        prod_category : 'electrical',
        txt_pack_type : '',
        prod_isReturnable : 'yes',
        prod_price_selling : '800',
        prod_discount : '12',
        prod_price_offer : '140',
        prod_price_total : '150',
        prod_discount_added : '10',
        prod_stock : '3',
        prod_expiry_date : '1/2/2222',
        txt_county : 'india',
    },
    {
        id : 7,
        prod_name : 'pizza',
        prod_image : '',
        prod_seller : 'jeo',
        prod_variant : '1',
        prod_category : 'food',
        txt_pack_type : '',
        prod_isReturnable : 'yes',
        prod_price_selling : '600',
        prod_discount : '12',
        prod_price_offer : '140',
        prod_price_total : '150',
        prod_discount_added : '10',
        prod_stock : '3',
        prod_expiry_date : '1/2/2222',
        txt_county : 'india',
    },
]